### ISSUE TITLE
Imports of S-100 schemas, relative or absolute

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-100WG#7]
Should the generic S-100 schemas for Edition 5.1.0 use relative or absolute URLs for:
1) Imports of other S-100 schemas
2) Imports of ISO and OGC schemas

For the 5.0 schemas I have heard different views from different people at different times.
Relative - meaning:
```xml
<xs:import namespace="http://www.iho.int/s100/se/5.1" schemaLocation="../../../5.1.0/S100SE/20230327/Part15.xsd"/>
```
Absolute - meaning:
```xml
<xs:import namespace="http://www.iho.int/s100/se/5.1" schemaLocation="https://schemas.s100dev.net/schemas/S100/5.1.0/S100SE/20230327/Part15.xsd"/>
```

For the S-100 schemas I can use either relative or absolute locations for imports, but cannot create one version with absolute and another with relative imports.
Before the discussion gets going I will remind everyone about "OASIS XML Catalogs" and "URI resolvers".

The ISO and OGC schemas import other schemas. The import statements within the ISO and OGC schemas would remain as is, i.e., as specified by ISO or OGC.

Views on this question ASAP particularly from:
@TDYCARHugh
@HolgerBothien
@DavidGrant-NIWC
@kusala9

**Comment by kusala9** [comment]
I'd really like relative schemas. It is far easier to work with schemas if the download from the IHO website is "standalone" and has no external dependencies. As an implementer I generate programmable interfaces from the schemas directly and for reasons of configuration management it is far far better to have all code artifacts which generate code to be within a source tree. Any external dependencies potentially can change and break software builds. 

The OASIS Catalogs and URI resolvers are ok as solutions but can be platform and implementation dependent and rely on support from (e.g.) source code build mechanisms and IDEs. 

The other aspect is to remember ECDIS OEMs will need to go through this process as well and, as a standalone piece of equipment, they will need to bundle in all the many referenced schemas as well. So, OEMs are likely to have to download and configure a resolver for all of the schemas as well. If relative imports are used then there is no need to adapt the IHO ones...

**Comment by TDYCARHugh** [comment]
If IHO is using relative paths then it seems it would be simpler to configure these for a stand-alone system.

**Comment by DavidGrant-NIWC** [comment]
I don't really have a preference either way, but whatever is done I hope we ensure that resolution is internally consistent. Most of the issues we have run into are the result of inconsistencies with the imports (specifically the OGC/GML stuff):
* S-100 imports an OGC schema which imports schema X.
* S-100 then imports a different version of schema X.
* The versions of schema X conflict with one another.

It's further complicated because S-100 may be using one type of referencing, but the imported schema is doing the opposite.

As I've noted previously, this would be greatly simplified if we profiled the GML stuff to the minimum necessary to support Part 17. Also, we should restrict the allowed encodings of `S100_BoundingPolygon_Type` (`gex:EX_BoundingPolygon_Type` is where most of the complexity comes from).

**Comment by HolgerBothien** [comment]
I don't have a preference here. schemaLocation is for me always only a hint and we use resolvers and XML catalogs to find the appropriate resources.

**Comment by rmalyankar** [comment]
Using relative imports by popular demand. Note that this means some of the imports in 5.1 schemas could reference 5.0 schemas.
