### ISSUE TITLE
Use of purpose in S100_CatalogueDiscoveryMetadata

### ISSUE THREAD

**Issue by TDYCARHugh** [iho-ohi/S-100WG#9]
In S-100 Ed 5.1 Part 17-4.5 under S100_CatalogueDiscoveryMetadata the remarks for the attribute 'purpose' states that the purpose my be one of new edition or cancellation which leaves the other possible values of S100_Purpose not available for use.  The XML schema appears to allow any of the S100_Purpose values.  Perhaps the remark is in error or is there some reason the purpose should have such restriction?

**Comment by rmalyankar** [comment]
As I recall it the constraint in the remark was specified because _newDataset_, _update_, _reIssue_, and _delta_ were considered inapplicable to catalogues and/or no one wanted to explore their implications and complications in the context of catalogues. S100_Purpose is also used in dataset discovery metadata. 

The constraint in the remark is enforced in the Schematron file for exchange catalogues, which is also on the schema server (presently the staging server, pending approval of Edition 5.1). The rule in that file emits a warning if the purpose in S100_CatalogueDiscoveryMetadata is not _newEdition_ or _cancellation_.  (There being no mandate in S-100 to use Schematron, implementations can enforce that and other constraints as best suits whatever context, framework, language, etc., they are designed for.)

**Comment by TDYCARHugh** [comment]
Thanks Raphael.  That answers my questions.  I was looking at the XSD and did not notice the restriction in the Schematron file.  I recommend this issue be closed.
